<?php

/**
 * PluginGatherDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginGatherDataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginGatherDataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginGatherData');
    }
}