<?php

/**
 * PluginGatherActivityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginGatherActivityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginGatherActivityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginGatherActivity');
    }

    

    public function getOrderdQuery(){
    	return $this->createQuery();#->orderBy('created_at DESC'); 
    }

#    public function findGatherDataId($gather_id){
#	$query = $this->getOrderdQuery();
#	$query->andWhere('gather_data_id = ?', $gather_id);
#	return $query->execute();
#    }
}
